repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      # Run the linter (auto-fixing issues where possible)
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format
